version: '3.8'
services:
  db-keycloak:
    image: postgres:15.4
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - D:/microservices-reader-notes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keypass
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    networks:
      - keycloak-network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST:  db-keycloak
      KC_URL_DATABASE: keycloak
      KC_DB_PASSWORD: keypass
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    ports:
      - 8880:8080
      - 80:8443
    networks:
      - keycloak-network
    depends_on:
      db-keycloak:
        condition: service_healthy


networks:
  keycloak-network:
    driver: bridge