eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: discovery-service

management:
  zipkin:
    tracing:
      endpoint: http://tempo:9411

