server:
  port: 8671

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost

  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
