global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'book-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['book-service:8080'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'book-search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['book-search-service:8080'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'notification-service'
    static_configs:
      - targets: [ 'notification-service:8080' ]
